### ISSUE TITLE
Missing copyright holder information in LICENSE

### ISSUE THREAD

**Issue by Calinou** [doceazedo/godot_wry#5]
Hello,

Copyright holder information in the license is missing (there are placeholders instead), could you add it?

https://github.com/doceazedo/godot_wry/blob/main/LICENSE#L3

**Comment by doceazedo** [comment]
Nice catch, thank you! Fixed here: https://github.com/doceazedo/godot_wry/commit/0253e3e5c9acc84e032ac2047181eeb106fb20d3
